[server]
maxUploadSize = 500
maxMessageSize = 500

[theme]
base = "light"
primaryColor = "#1F6F8B"
backgroundColor = "#F1F3F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D2229"
font = "sans serif"
